name: .NET CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: |
          find . -name "*.sln" -exec dotnet restore {} \;

      - name: Build
        run: |
          find . -name "*.sln" -exec dotnet build {} --configuration Release --no-restore \;

      - name: Test
        run: |
          find . -name "*.sln" -exec dotnet test {} --configuration Release --no-build --verbosity normal \;
